Fleshed out the python commands

diff --git a/.github/workflows/test-pull-request.yml b/.github/workflows/test-pull-request.yml
--- a/.github/workflows/test-pull-request.yml
+++ b/.github/workflows/test-pull-request.yml
@@ -64,8 +64,31 @@ jobs:
       with:
         command: bench
         args: --manifest-path lace/Cargo.toml --no-run
+    - name: Set up Python 3.10
+      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
+      uses: actions/setup-python@v3
+      with:
+        python-version: "3.10"
+    - name: Install python dependencies
+      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
+      run: |
+        python -m pip install --upgrade pip
+        pip install pytest maturin pyarrow polars pandas scipy plotly
+    - name: Check python formatting with black
+      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
+      uses: psf/black@stable
+      with:
+        options: --check --verbose
+        src: pylace/lace
+    - name: Build pylace
+      if: success() || faillure()
+      run: |
+        maturin develop --release -m pylace/core/Cargo.toml
+    - name: Test with pytest
+      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
+      run: |
+        pytest pylace
     - name: Remove failure skips. YOU CANNOT MERGE TO MASTER YET
       if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
       run: |
         false
-
