Change to use the official Pyo3 GitHub Action

diff --git a/.github/workflows/test-pull-request.yml b/.github/workflows/test-pull-request.yml
--- a/.github/workflows/test-pull-request.yml
+++ b/.github/workflows/test-pull-request.yml
@@ -116,10 +116,11 @@ jobs:
       with:
         options: --check --verbose
         src: pylace/lace
-    - name: Build pylace
-      if: success() || failure()
-      run: |
-        maturin develop --release -m pylace/core/Cargo.toml
+    - name: Build python wheel
+      if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
+      uses: PyO3/maturin-action@v1
+      with:
+        args: --release -m pylace/core/Cargo.toml
     - name: Test with pytest
       if: success() || failure() # Bypass failing steps for now. REMOVE THIS BEFORE MERGING TO MASTER!
       run: |
